"""
GrantRadar Pydantic Schemas
Request/Response models for API endpoints.
"""
# Common response schemas
from backend.schemas.common import (
    PaginatedResponse,
    PaginationInfo,
    create_paginated_response,
)
# TypedDict definitions for JSONB fields
from backend.schemas.jsonb_types import (
    ChecklistItemDict,
    WorkflowStageDict,
    TeamMemberPermissionsDict,
    ComplianceRuleItemDict,
    ComplianceScanResultDict,
    WorkflowEventMetadataDict,
    WorkflowMetricsDict,
    ReviewActionMetadataDict,
    StageTimeMetricsDict,
)
from backend.schemas.alerts import (
    AlertDeadlineSummary,
    AlertFrequency,
    AlertGrantSummary,
    FundingAlertPreferencesCreate,
    FundingAlertPreferencesResponse,
    FundingAlertPreview,
)
from backend.schemas.auth import (
    ForgotPasswordRequest,
    ForgotPasswordResponse,
    ResetPasswordRequest,
    ResetPasswordResponse,
    Token,
    TokenData,
    UserCreate,
    UserLogin,
    UserResponse,
)
from backend.schemas.grants import (
    GrantDetail,
    GrantFilter,
    GrantList,
    GrantResponse,
    GrantSearch,
)
from backend.schemas.matches import (
    MatchAction,
    MatchDetail,
    MatchFeedback,
    MatchFilter,
    MatchList,
    MatchResponse,
)
from backend.schemas.preferences import (
    DigestFrequency,
    NotificationPreferencesResponse,
    NotificationPreferencesUpdate,
)
from backend.schemas.profile import (
    LabProfileCreate,
    LabProfileResponse,
    LabProfileUpdate,
    OnboardingData,
)
from backend.schemas.saved_searches import (
    SavedSearchCreate,
    SavedSearchFilters,
    SavedSearchList,
    SavedSearchResponse,
    SavedSearchUpdate,
)
from backend.schemas.stats import DashboardStats
from backend.schemas.calendar import (
    CalendarDay,
    CalendarDeadlinesResponse,
    CalendarEvent,
    CalendarEventType,
    CalendarMonthResponse,
    UpcomingDeadline,
    UpcomingDeadlinesResponse,
    UrgencyLevel,
)
from backend.schemas.analytics import (
    CategoryBreakdownItem,
    CategoryBreakdownResponse,
    FundingDataPoint,
    FundingTrendsResponse,
    PipelineMetricsResponse,
    PipelineStageMetric,
    SuccessRateByCategory,
    SuccessRateByFunder,
    SuccessRateByStage,
    SuccessRatesResponse,
)
from backend.schemas.deadlines import (
    DeadlineCreate,
    DeadlineList,
    DeadlinePriority,
    DeadlineResponse,
    DeadlineStatus,
    DeadlineUpdate,
    LinkGrantRequest,
)
from backend.schemas.reminders import (
    BulkReminderCreate,
    ReminderScheduleCreate,
    ReminderScheduleResponse,
    ReminderSettingsResponse,
    ReminderSettingsUpdate,
)
from backend.schemas.integrations import (
    CalendarIntegrationResponse,
    CalendarStatusResponse,
    OAuthCallbackRequest,
    ProviderStatus,
    SyncResponse,
    UpdateIntegrationRequest,
)
from backend.schemas.templates import (
    TemplateCategoryResponse,
    TemplateCreate,
    TemplateListResponse,
    TemplateRenderRequest,
    TemplateRenderResponse,
    TemplateResponse,
    TemplateUpdate,
    TemplateVariable,
)
from backend.schemas.eligibility import (
    EligibilityStatus,
    EligibilityCriterion,
    EligibilityCheckRequest,
    EligibilityCheckResponse,
    EligibilityFollowUpRequest,
    EligibilityFollowUpResponse,
)
from backend.schemas.chat import (
    ChatSessionType,
    ChatSource,
    ChatMessageCreate,
    ChatMessageResponse,
    ChatSessionCreate,
    ChatSessionResponse,
    ChatSessionListItem,
)
from backend.schemas.research import (
    ResearchStatus,
    ResearchGrantResult,
    ResearchSessionCreate,
    ResearchSessionResponse,
    ResearchSessionListItem,
    ResearchQuickSearch,
)
from backend.schemas.kanban import (
    ApplicationStage,
    Priority,
    MemberRole,
    AttachmentCategory,
    FieldType,
    SubtaskBase,
    SubtaskCreate,
    SubtaskUpdate,
    SubtaskResponse,
    ActivityResponse,
    CommentCreate,
    AttachmentResponse,
    FieldOption,
    FieldDefinitionCreate,
    FieldDefinitionUpdate,
    FieldDefinitionResponse,
    FieldValuesUpdate,
    TeamInvite,
    LabMemberResponse,
    AssigneeResponse,
    AssigneesUpdate,
    CardUpdate,
    SubtaskProgress,
    KanbanCardResponse,
    ReorderRequest,
    SubtaskReorderRequest,
    BoardTotals,
    KanbanBoardResponse,
)
from backend.schemas.team import (
    InvitationStatus as TeamInvitationStatus,
    MemberRole as TeamMemberRole,
    ActivityType,
    EntityType,
    MemberPermissions,
    TeamInviteRequest,
    InvitationAcceptRequest,
    InvitationDeclineRequest,
    TeamMemberResponse,
    TeamMemberUpdate,
    TeamActivityResponse,
    TeamActivityFilters,
    TeamStatsResponse,
    TeamMembersListResponse,
    TeamActivitiesListResponse,
)

__all__ = [
    # Common response schemas
    "PaginatedResponse",
    "PaginationInfo",
    "create_paginated_response",
    # JSONB TypedDict definitions
    "ChecklistItemDict",
    "WorkflowStageDict",
    "TeamMemberPermissionsDict",
    "ComplianceRuleItemDict",
    "ComplianceScanResultDict",
    "WorkflowEventMetadataDict",
    "WorkflowMetricsDict",
    "ReviewActionMetadataDict",
    "StageTimeMetricsDict",
    # Alerts
    "AlertDeadlineSummary",
    "AlertFrequency",
    "AlertGrantSummary",
    "FundingAlertPreferencesCreate",
    "FundingAlertPreferencesResponse",
    "FundingAlertPreview",
    # Auth
    "ForgotPasswordRequest",
    "ForgotPasswordResponse",
    "ResetPasswordRequest",
    "ResetPasswordResponse",
    "Token",
    "TokenData",
    "UserCreate",
    "UserLogin",
    "UserResponse",
    # Grants
    "GrantDetail",
    "GrantFilter",
    "GrantList",
    "GrantResponse",
    "GrantSearch",
    # Matches
    "MatchAction",
    "MatchDetail",
    "MatchFeedback",
    "MatchFilter",
    "MatchList",
    "MatchResponse",
    # Preferences
    "DigestFrequency",
    "NotificationPreferencesResponse",
    "NotificationPreferencesUpdate",
    # Profile
    "LabProfileCreate",
    "LabProfileResponse",
    "LabProfileUpdate",
    "OnboardingData",
    # Saved Searches
    "SavedSearchCreate",
    "SavedSearchFilters",
    "SavedSearchList",
    "SavedSearchResponse",
    "SavedSearchUpdate",
    # Stats
    "DashboardStats",
    # Calendar
    "CalendarDay",
    "CalendarDeadlinesResponse",
    "CalendarEvent",
    "CalendarEventType",
    "CalendarMonthResponse",
    "UpcomingDeadline",
    "UpcomingDeadlinesResponse",
    "UrgencyLevel",
    # Analytics
    "CategoryBreakdownItem",
    "CategoryBreakdownResponse",
    "FundingDataPoint",
    "FundingTrendsResponse",
    "PipelineMetricsResponse",
    "PipelineStageMetric",
    "SuccessRateByCategory",
    "SuccessRateByFunder",
    "SuccessRateByStage",
    "SuccessRatesResponse",
    # Deadlines
    "DeadlineCreate",
    "DeadlineList",
    "DeadlinePriority",
    "DeadlineResponse",
    "DeadlineStatus",
    "DeadlineUpdate",
    "LinkGrantRequest",
    # Reminders
    "BulkReminderCreate",
    "ReminderScheduleCreate",
    "ReminderScheduleResponse",
    "ReminderSettingsResponse",
    "ReminderSettingsUpdate",
    # Integrations
    "CalendarIntegrationResponse",
    "CalendarStatusResponse",
    "OAuthCallbackRequest",
    "ProviderStatus",
    "SyncResponse",
    "UpdateIntegrationRequest",
    # Templates
    "TemplateCategoryResponse",
    "TemplateCreate",
    "TemplateListResponse",
    "TemplateRenderRequest",
    "TemplateRenderResponse",
    "TemplateResponse",
    "TemplateUpdate",
    "TemplateVariable",
    # Eligibility
    "EligibilityStatus",
    "EligibilityCriterion",
    "EligibilityCheckRequest",
    "EligibilityCheckResponse",
    "EligibilityFollowUpRequest",
    "EligibilityFollowUpResponse",
    # Chat
    "ChatSessionType",
    "ChatSource",
    "ChatMessageCreate",
    "ChatMessageResponse",
    "ChatSessionCreate",
    "ChatSessionResponse",
    "ChatSessionListItem",
    # Research
    "ResearchStatus",
    "ResearchGrantResult",
    "ResearchSessionCreate",
    "ResearchSessionResponse",
    "ResearchSessionListItem",
    "ResearchQuickSearch",
    # Kanban
    "ApplicationStage",
    "Priority",
    "MemberRole",
    "AttachmentCategory",
    "FieldType",
    "SubtaskBase",
    "SubtaskCreate",
    "SubtaskUpdate",
    "SubtaskResponse",
    "ActivityResponse",
    "CommentCreate",
    "AttachmentResponse",
    "FieldOption",
    "FieldDefinitionCreate",
    "FieldDefinitionUpdate",
    "FieldDefinitionResponse",
    "FieldValuesUpdate",
    "TeamInvite",
    "LabMemberResponse",
    "AssigneeResponse",
    "AssigneesUpdate",
    "CardUpdate",
    "SubtaskProgress",
    "KanbanCardResponse",
    "ReorderRequest",
    "SubtaskReorderRequest",
    "BoardTotals",
    "KanbanBoardResponse",
    # Team
    "TeamInvitationStatus",
    "TeamMemberRole",
    "ActivityType",
    "EntityType",
    "MemberPermissions",
    "TeamInviteRequest",
    "InvitationAcceptRequest",
    "InvitationDeclineRequest",
    "TeamMemberResponse",
    "TeamMemberUpdate",
    "TeamActivityResponse",
    "TeamActivityFilters",
    "TeamStatsResponse",
    "TeamMembersListResponse",
    "TeamActivitiesListResponse",
]
